baseURL: https://spatlyu.github.io
title: Wenbo Lv
theme: gokarna
languageCode: en
defaultContentLanguage: en
enableEmoji: yes
enableRobotsTXT: yes
pygmentsStyle: monokai
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
params:
  AvatarAltText: avatar
  ShowBackToTopButton: yes
  avatarSize: size-m
  avatarURL: /images/spatlyu.webp
  # customHeadHTML: "    <!-- KaTeX -->\r\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css\"
  #   integrity=\"sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC\"
  #   crossorigin=\"anonymous\">\r\n    <script defer src=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js\"
  #   integrity=\"sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja\"
  #   crossorigin=\"anonymous\"></script>\r\n    <script defer src=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js\"
  #   integrity=\"sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR\"
  #   crossorigin=\"anonymous\"></script>\r\n    <script>\r\n      document.addEventListener(\"DOMContentLoaded\",
  #   function() {\r\n        renderMathInElement(document.body, {\r\n          // customised
  #   options\r\n          // • auto-render specific keys, e.g.:\r\n          delimiters:
  #   [\r\n            {left: '$$', right: '$$', display: true},\r\n            {left:
  #   '$', right: '$', display: false},\r\n          ],\r\n          // • rendering
  #   keys, e.g.:\r\n          throwOnError : false\r\n        });\r\n      });\r\n
  #   \   </script>\r\n "
  customHeadHTML: |
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        tex2jax: {
          inlineMath: [['$','$'], ['\\(','\\)']],
          processEscapes: true
        }
      });
    </script>
    <script type="text/javascript" async
      src="https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-MML-AM_CHTML">
    </script>

  description: Geoinformatics; Statistics; R; C++; Python
  footer: SpatLyu
  metaKeywords:
    - blog
    - gokarna
    - hugo
  socialIcons:
    - name: github
      url: https://github.com/SpatLyu
    - name: mastodon
      url: https://mastodon.social/@SpatLyu
    - name: orcid
      url: https://orcid.org/0009-0002-6003-3800
    - name: zhihu
      url: https://www.zhihu.com/people/lyu-geosocial
    - name: bilibili
      url: https://b23.tv/g1qp0uU
    - name: resume
      url: https://spatlyu.github.io/materials/cv.pdf
    - name: email
      url: mailto:lyu.geosocial@gmail.com
    # - name: rocket
    #   url: https://spatlyu.r-universe.dev/

menu:
  main:
    - name: Home
      pre: <span data-feather='home'></span>
      url: /
      weight: 1
    - name: Posts
      pre: <span data-feather='book'></span>
      url: /posts/
      weight: 2
    - name: Projects
      pre: <span data-feather='code'></span>
      url: /projects/
      weight: 3
    - name: Tags
      pre: <span data-feather='tag'></span>
      url: /tags/
      weight: 4
    - identifier: github
      pre: <span data-feather='github'></span>
      url: https://github.com/SpatLyu
      weight: 5
    - identifier: rss
      pre: <span data-feather='rss'></span>
      url: /index.xml
      weight: 7
markup:
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 1
  goldmark:
    renderer:
      unsafe: true

